version: '3'
services:
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - '3050:80'
  mongo:
    image: 'mongo:latest'
  api:
    depends_on:
      - mongo
    build:
      dockerfile: Dockerfile.dev
      context: ./API
    volumes:
      - /app/node_modules
      - ./API:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/proyecto1
    # ports:
    #   - '5000:5000'
  client:
    build:
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
